`timescale 1ns/1ps

module half_adder_tb;

reg a, b;
wire sum, carry;

half_adder uut(
    .a(a),
    .b(b),
    .sum(sum),
    .carry(carry)
);

initial begin
    $dumpfile("half_adder.vcd");
    $dumpvars(0, uut);

    a=0; b=0; #100;
    a=0; b=1; #100;
    a=1; b=0; #100;
    a=1; b=1; #100;
    // $finish;
end

// initial begin
//     $monitor("t=%0t | a=%b b=%b | sum=%b carry=%b", $time, a, b, sum, carry);
// end

endmodule